# Site settings
title: plainlanguage.gov
description: Plain language makes it easier for the public to read, understand, and use government communications.
email: plainlanguage@gsa.gov
facebook: https://www.facebook.com/plainlanguagegov-174397429237337/
twitter: https://twitter.com/govplainlang/
repo: https://github.com/GSA/plainlanguage.gov

sitewide_notification:
  display: false
  heading: Information Status
  text: >
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.

theme: uswds-jekyll

plugins:
  - jekyll-redirect-from

exclude:
  - CONTRIBUTING.md
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - vendor
  - webpack.config.js

scripts:
  - /assets/js/build/bundle.js

styles:
  - href: /assets/css/main.css
    media: screen, print

sass:
  load_paths:
    - _sass
    - node_modules

defaults:
  - scope:
      path: "assets/uswds"
    values:
      skip_index: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "docs"

collections:
  pages:
    output: true
    permalink: /:path/

kramdown:
  parse_block_html: true

jekyll_pages_api_search:
  skip_index: false
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
