# Site settings
title: plainlanguage.gov
description: Resources to help federal employees deliver clear communications to the public.

# Using https://github.com/18F/uswds-jekyll
theme: uswds-jekyll

# GA and GitHub data
# google_analytics_ua: UA-99995535-1
repo: https://github.com/GSA/plainlanguage.gov

gems:
  - jekyll-redirect-from

exclude:
  - CONTRIBUTING.md
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - node_modules
  - package.json
  - README.md
  - vendor

styles:
  - /assets/css/main.css

sass:
    load_paths:
        - _sass
        - node_modules

defaults:
  - scope:
      path: ""
      type: "guidelines"
    values:
      layout: "docs"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "docs"

collections:
  guidelines:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:path/

kramdown:
  parse_block_html: true
