version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Run Federalist npm script
          command: npm run federalist
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Build site
          command: bundle exec jekyll build
      - run:
          name: Test with htmlproofer
          command: bundle exec htmlproofer ./_site --allow-hash-href=true --disable-external=true --enforce-https=false --ignore-empty-alt=false --ignore-empty-alt=true
